### ISSUE TITLE
Trying to export all log files on Android fails with ENAMETOOLONG

### ISSUE THREAD

**Issue by MrCsabaToth** [umair13adil/flutter_logs#27]
How I initialize:
```
    FlutterLogs.setDebugLevel(0);
    final List<LogLevel> logLevels = logLevelThreshold == logLevelNone ? [] : [LogLevel.INFO, LogLevel.WARNING, LogLevel.ERROR, LogLevel.SEVERE];
    await FlutterLogs.initLogs(
      logLevelsEnabled: logLevels,
      timeStampFormat: TimeStampFormat.TIME_FORMAT_READABLE,
      directoryStructure: DirectoryStructure.FOR_DATE,
      logTypesEnabled: ["device", "network", "errors"],
      logFileExtension: LogFileExtension.TXT,
      logsWriteDirectoryName: "Logs",
      logsExportDirectoryName: "Logs/Exported",
      debugFileOperations: kDebugMode,
      isDebuggable: kDebugMode,
    );
```

Then when I `FlutterLogs.exportLogs(exportType: ExportType.ALL);` I get:

> W/System.err(23985): java.io.FileNotFoundException: /storage/emulated/0/Android/data/dev.csaba.track_my_indoor_exercise/files/Logs/Logs/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Export
W/System.err(23985): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err(23985): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W/System.err(23985): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err(23985): 	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:236)
W/System.err(23985): 	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
W/System.err(23985): 	at kotlin.io.FilesKt__UtilsKt.copyRecursively(Utils.kt:328)
W/System.err(23985): 	at kotlin.io.FilesKt__UtilsKt.copyRecursively$default(Utils.kt:288)
W/System.err(23985): 	at com.blackbox.plog.pLogs.filter.FileFilter.getFilesForAll(Unknown Source:40)
W/System.err(23985): 	at com.blackbox.plog.pLogs.exporter.ExportTypesKt.getLogsForAllInRoot(Unknown Source:10)
W/System.err(23985): 	at com.blackbox.plog.pLogs.exporter.ExportTypesKt.getFilesForRequestedType(Unknown Source:85)
W/System.err(23985): 	at com.blackbox.plog.pLogs.exporter.LogExporter$getZippedLogs$1.subscribe(Unknown Source:26)
W/System.err(23985): 	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
W/System.err(23985): 	at io.reactivex.Observable.subscribe(Observable.java:12267)
W/System.err(23985): 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
W/System.err(23985): 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
W/System.err(23985): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
W/System.err(23985): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err(23985): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(23985): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err(23985): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(23985): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(23985): 	at java.lang.Thread.run(Thread.java:923)
W/System.err(23985): Caused by: android.system.ErrnoException: open failed: ENAMETOOLONG (File name too long)
W/System.err(23985): 	at libcore.io.Linux.open(Native Method)
W/System.err(23985): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(23985): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err(23985): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(23985): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7885)
W/System.err(23985): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(23985): 	... 21 more
E/PLogger (23985): {FlutterLogsPlugin}  {exportPLogs}  {PLog Error: /storage/emulated/0/Android/data/dev.csaba.track_my_indoor_exercise/files/Logs/Logs/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/Exported/Temp/E
E/PLogger (23985):

**Comment by MrCsabaToth** [comment]
I got it working with some adjustment. I still don't know how the endless name above forms.

```
static String fileName = "DebugLog";
...

    if (!kDebugMode) {
      FlutterLogs.setDebugLevel(0);
    }

    final List<LogLevel> logLevels = logLevelThreshold == logLevelNone
        ? []
        : [LogLevel.INFO, LogLevel.WARNING, LogLevel.ERROR, LogLevel.SEVERE];
    await FlutterLogs.initLogs(
      logLevelsEnabled: logLevels,
      timeStampFormat: TimeStampFormat.TIME_FORMAT_READABLE,
      directoryStructure: DirectoryStructure.FOR_DATE,
      logTypesEnabled: [fileName],
      logFileExtension: LogFileExtension.TXT,
      logsWriteDirectoryName: "Logs",
      logsExportDirectoryName: "Exported",
      logsExportZipFileName: "LogExport",
      debugFileOperations: kDebugMode,
      isDebuggable: kDebugMode,
    );
```

**Comment by acalatrava** [comment]
I'm getting this same error on Android with latest version, any hints?
