### ISSUE TITLE
PlatformException while setting meta info

### ISSUE THREAD

**Issue by niels-beier** [umair13adil/flutter_logs#44]
When trying to set the meta info a PlatformException occurs:
```PlatformException (PlatformException(error, empty String, null, java.lang.NumberFormatException: empty String
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at com.flutter.logs.plogs.flutter_logs.LogsHelper.setupForELKStack(LogsHelper.kt:156)
    at com.flutter.logs.plogs.flutter_logs.FlutterLogsPlugin$Companion.setUpPluginMethods$lambda-0(FlutterLogsPlugin.kt:150)
    at com.flutter.logs.plogs.flutter_logs.FlutterLogsPlugin$Companion.$r8$lambda$KCO-SFXW70ZXiuPV_Lwf9VhDIMM(Unknown Source:0)
    at com.flutter.logs.plogs.flutter_logs.FlutterLogsPlugin$Companion$$ExternalSyntheticLambda0.onMethodCall(Unknown Source:2)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
    at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
))```
It happens no matter what arguments are being set and how.

**Comment by Akiyamka** [comment]
Somebody found an workaround for this?

**Comment by izludec** [comment]
It seems like somewhere in native library pased latitude and longitude throw this error. For quick fix you can set this fields to some number.

```
      latitude: "1",
      longitude: "1",
```
